### ISSUE TITLE
MacOS Apple Silicon ?

### ISSUE THREAD

**Issue by johann-taberlet** [hafriedlander/stable-diffusion-grpcserver#20]
Automatic1111 works pretty well on my M1 pro so I'm wondering if your server does as well and if yes, if there is some doc on the how to ?
Thanks :)

**Comment by hafriedlander** [comment]
Hi. Unfortunately I don't have an M1 Mac. The underlying library (Diffusers) does support Macs, but because I can't test it I've almost certainly broken it in this server.

If some developer wanted to commit to maintaining Mac support I'd be happy, but unless that happens this project probably won't support Macs anytime in the near future.
