### ISSUE TITLE
Inpainting: contrast in surrounding

### ISSUE THREAD

**Issue by imperator-maximus** [hafriedlander/stable-diffusion-grpcserver#4]
Hi,

Inpainting works. But all the surrounding pixels are getting a contrast change.
Example (zoomed-in):
![image](https://user-images.githubusercontent.com/4406586/193475423-1fc1a834-e3f5-4f0c-983d-b4669ce647e8.png)

In comparison to Img2Img vom Automatic1111 with Latent Noise ( all ok):
![image](https://user-images.githubusercontent.com/4406586/193475439-27b7c61e-f65a-4711-8f66-723083be3798.png)

I am using strength 1.0 btw

**Comment by hafriedlander** [comment]
Yeah, I know why this is happening. The whole image is moved through the latent space and back, even the protected portions, and that results in a slight change in the protected portion.

The fix is to mask the protected portion back in afterwards. Note that you _will_ get some changes in the partially protected portion - only the completely protected portion will be masked in (otherwise you get ghosting in the partially protected portion where the latent space has shifted to accommodate the inpaint).

I'll prioritize fixing this, because it annoys me too :).

**Comment by hafriedlander** [comment]
This should be fixed now. Not that it only will be fixed when strength is exactly 1 (thinking about it, we probably want it for lower strength in inpaint-over-pixels mode too, just not for greater than 1)

**Comment by imperator-maximus** [comment]
This works fine now. Thank you!
